[package]
name = "faktor-provider"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
[dependencies]
faktor-core.workspace = true
faktor-protocol.workspace = true
reqwest = { version = "0.13", default-features = false, features = ["json", "stream", "native-tls", "http2"] }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
thiserror.workspace = true
tracing.workspace = true
tempfile.workspace = true
