// The Faktor Native Protocol v1 client (docs/native-protocol.md): a typed
// java.net.http client of the daemon's OWN surface. The frozen v7.5.6 wire
// surface in BackendProcessManager stays untouched migration glue; this
// client is what the real frontend renders from.
//
// Rules observed:
//  - auth is the ephemeral password generated by BackendProcessManager and
//    handed to the child through the environment (protected channel, never
//    argv or disk): `Authorization: Bearer <password>`.
//  - every response body is read through a streaming byte cap; oversized
//    bodies are closed and rejected, never buffered unbounded.
//  - every request carries a timeout; non-2xx bodies are mapped to
//    NativeApiException with the daemon's `{error:{code,message,retryable}}`.
//  - shapes are parsed by dev.faktor.shared native parsers, so drift is a
//    loud NativeProtocolException, never a silently wrong UI.
package dev.faktor.backend

import dev.faktor.shared.JsonCodec
import dev.faktor.shared.JsonValue
import dev.faktor.shared.NativeAbortAck
import dev.faktor.shared.NativeAgent
import dev.faktor.shared.NativeAgentControlAck
import dev.faktor.shared.NativeApiException
import dev.faktor.shared.NativeEventPage
import dev.faktor.shared.NativeEvidence
import dev.faktor.shared.NativeEvidenceRetrieval
import dev.faktor.shared.NativeHealth
import dev.faktor.shared.NativeMessagePage
import dev.faktor.shared.NativeModelInfo
import dev.faktor.shared.NativeProjection
import dev.faktor.shared.NativePromptReceipt
import dev.faktor.shared.NativeOrchestratorGraph
import dev.faktor.shared.NativePermissionAck
import dev.faktor.shared.NativePermissionEntry
import dev.faktor.shared.NativeProtocolException
import dev.faktor.shared.NativeReady
import dev.faktor.shared.NativeRequests
import dev.faktor.shared.NativeSessionCreated
import dev.faktor.shared.NativeSessionSummary
import dev.faktor.shared.NativeSessionUsage
import dev.faktor.shared.NativeTaskRun
import dev.faktor.shared.NativeTaskRunCancelled
import dev.faktor.shared.NativeTaskRunStarted
import dev.faktor.shared.NativeTaskVerification
import dev.faktor.shared.NativeTaskView
import dev.faktor.shared.NativeTournament
import dev.faktor.shared.NativeTournamentStarted
import dev.faktor.shared.NativeUsageTotals
import dev.faktor.shared.NativeVerificationView
import dev.faktor.shared.parseNativeAbortAck
import dev.faktor.shared.parseNativeAgentControlAck
import dev.faktor.shared.parseNativeAgents
import dev.faktor.shared.parseNativeEventPage
import dev.faktor.shared.parseNativeEvidence
import dev.faktor.shared.parseNativeEvidenceRetrieval
import dev.faktor.shared.parseNativeHealth
import dev.faktor.shared.parseNativeMessagePage
import dev.faktor.shared.parseNativeModelCatalog
import dev.faktor.shared.parseNativeOrchestratorGraph
import dev.faktor.shared.parseNativePermissionAck
import dev.faktor.shared.parseNativePermissionList
import dev.faktor.shared.parseNativeProjection
import dev.faktor.shared.parseNativePromptReceipt
import dev.faktor.shared.parseNativeReady
import dev.faktor.shared.parseNativeSessionCreated
import dev.faktor.shared.parseNativeSessionList
import dev.faktor.shared.parseNativeSessionUsage
import dev.faktor.shared.parseNativeTaskRunCancelled
import dev.faktor.shared.parseNativeTaskRunStarted
import dev.faktor.shared.parseNativeTaskRuns
import dev.faktor.shared.parseNativeTaskVerification
import dev.faktor.shared.parseNativeTaskViews
import dev.faktor.shared.parseNativeTournament
import dev.faktor.shared.parseNativeTournamentStarted
import dev.faktor.shared.parseNativeUsage
import dev.faktor.shared.parseNativeVerificationView
import java.io.ByteArrayOutputStream
import java.io.IOException
import java.io.InputStream
import java.net.URI
import java.net.URLEncoder
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.time.Duration

private const val REQUEST_ERROR_SNIPPET = 400

/**
 * Typed client of the daemon's native surface. One instance per daemon
 * connection; [bearerToken] is the connection password and never logged.
 */
class NativeClient(
    val baseUrl: String,
    val bearerToken: String,
    private val timeoutMs: Long = DEFAULT_TIMEOUT_MS,
    private val maxBodyBytes: Long = DEFAULT_MAX_BODY_BYTES
) {
    companion object {
        const val DEFAULT_TIMEOUT_MS = 15_000L
        const val DEFAULT_MAX_BODY_BYTES = 4L * 1024 * 1024
        const val EVIDENCE_MAX_BODY_BYTES = 32L * 1024 * 1024
        const val READY_POLL_MS = 100L

        fun forConnection(connection: BackendConnection): NativeClient =
            NativeClient(connection.baseUrl, connection.password)
    }

    private val http: HttpClient = HttpClient.newBuilder()
        .connectTimeout(Duration.ofMillis(timeoutMs))
        .build()

    // ------------------------------------------------------------ liveness

    fun health(): NativeHealth = parseNativeHealth(request("GET", "/native/health"))

    fun ready(): NativeReady = parseNativeReady(request("GET", "/native/ready"))

    /** Polls readiness until true or the deadline; returns the last ready state. */
    fun awaitReady(timeoutMs: Long = 10_000L): NativeReady {
        val deadline = System.currentTimeMillis() + timeoutMs
        var last = NativeReady(false)
        while (System.currentTimeMillis() < deadline) {
            last = try {
                ready()
            } catch (e: NativeApiException) {
                if (e.status != 503) throw e
                NativeReady(false)
            }
            if (last.ready) return last
            Thread.sleep(READY_POLL_MS)
        }
        return last
    }

    // ------------------------------------------------------------- sessions

    fun createSession(
        provider: String,
        model: String,
        workspace: String? = null,
        title: String? = null
    ): NativeSessionCreated = parseNativeSessionCreated(
        request(
            "POST", "/session/create", null,
            NativeRequests.createSession(provider, model, workspace, title)
        )
    )

    fun listSessions(): List<NativeSessionSummary> =
        parseNativeSessionList(request("GET", "/session/list"))

    fun modelCatalog(): List<NativeModelInfo> =
        parseNativeModelCatalog(request("GET", "/models"))

    fun prompt(sessionId: String, prompt: String, files: List<String>? = null): NativePromptReceipt =
        parseNativePromptReceipt(
            request(
                "POST", "/session/prompt", null,
                NativeRequests.prompt(sessionId, prompt, files)
            )
        )

    fun abortSession(sessionId: String, opId: String? = null): NativeAbortAck =
        parseNativeAbortAck(
            request(
                "POST", "/native/session/" + encode(sessionId) + "/abort", null,
                NativeRequests.abort(sessionId, opId)
            )
        )

    fun projection(sessionId: String): NativeProjection =
        parseNativeProjection(
            request("GET", "/session/" + encode(sessionId) + "/projection")
        )

    fun messages(sessionId: String, before: Long? = null, limit: Long? = null): NativeMessagePage =
        parseNativeMessagePage(
            request(
                "GET", "/native/messages",
                query("session" to sessionId, "before" to before?.toString(), "limit" to limit?.toString())
            )
        )

    fun events(sessionId: String, after: Long? = null, limit: Long? = null): NativeEventPage =
        parseNativeEventPage(
            request(
                "GET", "/native/events",
                query("session" to sessionId, "after" to after?.toString(), "limit" to limit?.toString())
            )
        )

    // ------------------------------------------------------------ task runs

    fun taskRuns(sessionId: String): List<NativeTaskRun> = parseNativeTaskRuns(
        request("GET", "/native/session/" + encode(sessionId) + "/task-runs")
    )

    fun taskRunState(sessionId: String, runId: String): NativeTaskRun {
        val runs = taskRuns(sessionId)
        for (run in runs) {
            if (run.runId == runId) return run
        }
        throw NativeApiException(404, "not_found", "task run $runId under session $sessionId", false)
    }

    fun startTaskRun(
        sessionId: String,
        goal: String,
        criteria: List<String>? = null,
        model: String? = null,
        maxTokens: Long? = null,
        maxCostMicro: Long? = null,
        mutationMode: String? = null,
        files: List<String>? = null
    ): NativeTaskRunStarted = parseNativeTaskRunStarted(
        request(
            "POST", "/native/session/" + encode(sessionId) + "/task-runs", null,
            NativeRequests.startTaskRun(
                goal, criteria, model, maxTokens, maxCostMicro, mutationMode, files
            )
        )
    )

    fun cancelTaskRun(sessionId: String, runId: String): NativeTaskRunCancelled =
        parseNativeTaskRunCancelled(
            request(
                "POST",
                "/native/session/" + encode(sessionId) + "/task-runs/" + encode(runId) + "/cancel"
            )
        )

    fun taskViews(sessionId: String): List<NativeTaskView> = parseNativeTaskViews(
        request("GET", "/native/session/" + encode(sessionId) + "/tasks")
    )

    // ------------------------------------------------------------ tournaments

    fun startTournament(
        sessionId: String,
        goal: String,
        criteria: List<String>,
        n: Int,
        model: String? = null,
        maxTokens: Long? = null,
        maxCostMicro: Long? = null,
        mutationMode: String? = null,
        files: List<String>? = null
    ): NativeTournamentStarted = parseNativeTournamentStarted(
        request(
            "POST", "/native/session/" + encode(sessionId) + "/tournament", null,
            NativeRequests.startTournament(
                goal, criteria, n, model, maxTokens, maxCostMicro, mutationMode, files
            )
        )
    )

    fun tournamentState(sessionId: String, tournamentId: String): NativeTournament =
        parseNativeTournament(
            request(
                "GET",
                "/native/session/" + encode(sessionId) + "/tournament/" + encode(tournamentId)
            )
        )

    // ------------------------------------------------------- orchestrator graph

    fun orchestratorGraph(sessionId: String): NativeOrchestratorGraph =
        parseNativeOrchestratorGraph(
            request("GET", "/native/orchestrator/graph", query("session" to sessionId))
        )

    // ------------------------------------------------- permissions (reply path)

    fun permissions(sessionId: String): List<NativePermissionEntry> =
        parseNativePermissionList(
            request("GET", "/permission/list", query("session_id" to sessionId))
        )

    fun replyPermission(permissionId: String, decision: String): NativePermissionAck =
        parseNativePermissionAck(
            request(
                "POST", "/permission/reply", null,
                NativeRequests.permissionReply(permissionId, decision)
            )
        )

    // --------------------------------------------------------------- agents

    fun agents(sessionId: String): List<NativeAgent> = parseNativeAgents(
        request("GET", "/native/agents", query("session" to sessionId))
    )

    fun pauseAgent(childId: String): NativeAgentControlAck = agentControl(childId, "pause")

    fun resumeAgent(childId: String): NativeAgentControlAck = agentControl(childId, "resume")

    fun cancelAgent(childId: String): NativeAgentControlAck = agentControl(childId, "cancel")

    fun retryAgent(childId: String): NativeAgentControlAck = agentControl(childId, "retry")

    fun steerAgent(childId: String, text: String): NativeAgentControlAck =
        parseNativeAgentControlAck(
            request(
                "POST", "/native/agents/" + encode(childId) + "/steer", null,
                NativeRequests.steer(text)
            )
        )

    fun setAgentModel(childId: String, model: String): NativeAgentControlAck =
        parseNativeAgentControlAck(
            request(
                "POST", "/native/agents/" + encode(childId) + "/model", null,
                NativeRequests.changeModel(model)
            )
        )

    fun setAgentBudget(
        childId: String,
        maxTokens: Long? = null,
        maxCostMicro: Long? = null
    ): NativeAgentControlAck {
        if ((maxTokens == null) == (maxCostMicro == null)) {
            throw NativeProtocolException(
                "setAgentBudget",
                "exactly one of maxTokens or maxCostMicro must be set"
            )
        }
        return parseNativeAgentControlAck(
            request(
                "POST", "/native/agents/" + encode(childId) + "/budget", null,
                NativeRequests.changeBudget(maxTokens, maxCostMicro)
            )
        )
    }

    private fun agentControl(childId: String, action: String): NativeAgentControlAck =
        parseNativeAgentControlAck(
            request("POST", "/native/agents/" + encode(childId) + "/" + action)
        )

    // ------------------------------------------------------ usage / verification

    fun usage(): NativeUsageTotals = parseNativeUsage(request("GET", "/native/usage"))

    fun sessionUsage(sessionId: String): NativeSessionUsage = parseNativeSessionUsage(
        request("GET", "/native/session/" + encode(sessionId) + "/usage")
    )

    fun verification(sessionId: String): NativeVerificationView = parseNativeVerificationView(
        request("GET", "/native/session/" + encode(sessionId) + "/verification")
    )

    fun taskVerification(sessionId: String, taskId: String): NativeTaskVerification =
        parseNativeTaskVerification(
            request(
                "GET",
                "/native/session/" + encode(sessionId) + "/tasks/" + encode(taskId) + "/verification"
            )
        )

    // ------------------------------------------------------------- evidence

    fun evidence(sessionId: String, evidenceId: Long): NativeEvidence = parseNativeEvidence(
        request(
            "GET", "/native/evidence/" + evidenceId,
            query("session" to sessionId)
        )
    )

    fun retrieveEvidence(
        sessionId: String,
        evidenceId: Long,
        selectorJson: String
    ): NativeEvidenceRetrieval = parseNativeEvidenceRetrieval(
        request(
            "POST", "/native/evidence/" + evidenceId + "/retrieve",
            query("session" to sessionId), selectorJson,
            EVIDENCE_MAX_BODY_BYTES
        )
    )

    // ------------------------------------------------------------- transport

    private fun query(vararg pairs: Pair<String, String?>): List<Pair<String, String>> {
        val out = ArrayList<Pair<String, String>>()
        for (pair in pairs) {
            if (pair.second != null) out.add(Pair(pair.first, pair.second!!))
        }
        return out
    }

    private fun encode(value: String): String = URLEncoder.encode(value, "UTF-8")

    private fun request(
        method: String,
        path: String,
        queryParams: List<Pair<String, String>>? = null,
        body: String? = null,
        maxBytes: Long = maxBodyBytes
    ): String {
        val url = StringBuilder(baseUrl.trimEnd('/')).append(path)
        if (queryParams != null && queryParams.isNotEmpty()) {
            url.append('?')
            for ((i, pair) in queryParams.withIndex()) {
                if (i > 0) url.append('&')
                url.append(encode(pair.first)).append('=').append(encode(pair.second))
            }
        }
        val builder = HttpRequest.newBuilder(URI.create(url.toString()))
            .timeout(Duration.ofMillis(timeoutMs))
            .header("Authorization", "Bearer $bearerToken")
            .header("Accept", "application/json")
        if (body != null) {
            builder.header("Content-Type", "application/json")
            builder.method(method, HttpRequest.BodyPublishers.ofString(body))
        } else {
            builder.method(method, HttpRequest.BodyPublishers.noBody())
        }
        val response = try {
            http.send(builder.build(), HttpResponse.BodyHandlers.ofInputStream())
        } catch (e: IOException) {
            throw NativeApiException(
                0, "transport",
                "$method $path failed (daemon down?): ${e.message}", true
            )
        } catch (e: InterruptedException) {
            Thread.currentThread().interrupt()
            throw NativeApiException(0, "transport", "$method $path interrupted", true)
        }
        val status = response.statusCode()
        val text = response.body().use { readBounded(it, maxBytes, "$method $path") }
        if (status !in 200..299) {
            throw apiError(status, text, "$method $path")
        }
        return text
    }

    /** Reads at most [maxBytes]; an oversized body is closed and rejected. */
    private fun readBounded(stream: InputStream, maxBytes: Long, path: String): String {
        val out = ByteArrayOutputStream()
        val buffer = ByteArray(8192)
        var total = 0L
        while (true) {
            val read = stream.read(buffer)
            if (read < 0) break
            total += read
            if (total > maxBytes) {
                throw NativeProtocolException(path, "response body exceeded bound $maxBytes bytes")
            }
            out.write(buffer, 0, read)
        }
        return String(out.toByteArray(), Charsets.UTF_8)
    }

    /** Maps a non-2xx body onto the daemon's typed error envelope. */
    private fun apiError(status: Int, body: String, path: String): NativeApiException {
        val parsed = try {
            JsonCodec.parse(body)
        } catch (e: NativeProtocolException) {
            return NativeApiException(status, "http_error", body.take(REQUEST_ERROR_SNIPPET), false)
        }
        val error = (parsed as? JsonValue.Obj)?.fields?.get("error") as? JsonValue.Obj
        val code = ((error?.fields?.get("code")) as? JsonValue.Str)?.value
        val message = ((error?.fields?.get("message")) as? JsonValue.Str)?.value
        val retryable = ((error?.fields?.get("retryable")) as? JsonValue.Bool)?.value
        if (code == null || message == null) {
            return NativeApiException(status, "http_error", body.take(REQUEST_ERROR_SNIPPET), false)
        }
        return NativeApiException(status, code, message, retryable == true)
    }
}
